#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: tuxY2 nºbancada"
	exit 1
fi

# configuração do IP
ifconfig eth0 up
ifconfig eth0 172.16.$11.1/24

# route para aceder a vlan 0 a partir de eth1 de tux14
route add -net 172.16.$10.0/24 gw 172.16.$11.253

# route para aceder a internet a partir de eth0 de router
route add -net default gw 172.16.$11.254

echo '

'
# ver routes
route -n

echo "

Verificar se existem estas 3 routes:
-	0.0.0.0		172.16.$11.254		0.0.0.0
-	172.16.$10.0	172.16.$11.253		255.255.255.0
-	172.16.$11.0	0.0.0.0			255.255.255.0
"

sleep 10

echo '



'

cat /etc/resolv.conf

echo "

Verififcar se existem, PELO MENOS, estas 2 linhas
search netlab.fe.up.pt
nameserver 172.16.1.1

Caso não existam as duas linhas fazer
nano /etc/resolv.conf
adicionar as linhas ao ficheiro
"