#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: tuxY4 nºbancada"
	exit 1
fi

# configuração de IP's
ifconfig eth0 up
ifconfig eth0 172.16.$10.254/24

ifconfig eth1 up
ifconfig eth1 172.16.$11.253/24

# Enable IP forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
# Disable ICMP echo-ignore-broadcast
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

# route para aceder a internet a partir de eth0 de router
route add -net default gw 172.16.$11.254

# ver routes
route -n

echo "

Verificar se existem estas 3 routes:
-	0.0.0.0			172.16.$11.254		0.0.0.0
-	172.16.$10.0		0.0.0.0 		255.255.255.0
-	172.16.$11.0		0.0.0.0			255.255.255.0
"

sleep 10

echo '



'

cat /etc/resolv.conf

echo "

Verififcar se existem, PELO MENOS, estas 2 linhas
search netlab.fe.up.pt
nameserver 172.16.1.1

Caso não existam as duas linhas fazer
nano /etc/resolv.conf
adicionar as linhas ao ficheiro
"